version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - export AWS_REGION=AWS_DEFAULT_REGION
            - export ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
            - export ECR_REGISTRY="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    build:
        commands:
            - echo Building the Docker image...
            - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            - docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
    post_build:
        commands:
            - echo Pushing the Docker image...
            - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
            - echo Build completed on `date`

artifacts:
    files:
        - appspec.yml
        - scripts/**/*
